"""key to station

Revision ID: 419d87a7ea5f
Revises: 4f71deffa9e0
Create Date: 2019-09-15 19:34:48.890669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419d87a7ea5f'
down_revision = '4f71deffa9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('key', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'station', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station', type_='unique')
    op.drop_column('station', 'key')
    # ### end Alembic commands ###
