"""empty message

Revision ID: b8d85678a28b
Revises: 
Create Date: 2019-07-12 20:36:50.335094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d85678a28b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('broadcaster', sa.Column('broadcast_pid', sa.String(length=20), nullable=True))
    op.add_column('broadcaster', sa.Column('show_name', sa.String(length=100), nullable=True))
    op.add_column('broadcaster', sa.Column('station_id', sa.Integer(), nullable=True))
    op.drop_constraint('broadcaster_name_key', 'broadcaster', type_='unique')
    op.create_foreign_key(None, 'broadcaster', 'station', ['station_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'broadcaster', type_='foreignkey')
    op.create_unique_constraint('broadcaster_name_key', 'broadcaster', ['name'])
    op.drop_column('broadcaster', 'station_id')
    op.drop_column('broadcaster', 'show_name')
    op.drop_column('broadcaster', 'broadcast_pid')
    op.drop_table('episode')
    # ### end Alembic commands ###
