[default]
name = "radioshaped"

  
    host = ""
    username =  ""
    password = "" 
    port = 5432
    database = "radioshaped"

[development]
debug = true

[production]
debug = false


[database]
